version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: indolingua-db-test
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: indolingua_test_db
    ports:
      - '5433:5432' # PENTING: Port Host 5433 dipetakan ke Container 5432
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data: