version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: indolingua-db
    restart: always
    environment:
      # Menggunakan syntax ${VARIABLE:-default}
      # Jika di .env ada, pakai itu. Jika tidak, pakai default (aman untuk dev lokal)
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-indolingua_db}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: